# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

@host={{$dotenv ENDPOINT_URI}}
### GET BICINCITTA ACCESS TOKEN
# @name login
POST {{$dotenv ENDPOINT_OAUTH_URI}}
Content-Type: application/x-www-form-urlencoded

&grant_type=client_credentials
&client_id={{$dotenv ENDPOINT_OAUTH_CLIENT_ID}}
&client_secret={{$dotenv ENDPOINT_OAUTH_CLIENT_SECRET}}

###
@token = {{login.response.body.access_token}}

### GET services
GET {{$dotenv ENDPOINT_URI}}/resources/stations
Authorization: Bearer {{token}}
###
