##### VSCODE / REST Client https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# Create a .env file and set the corresponding variables
# See all $dotenv fields below

# other vars
@url = http://localhost:9001/trigger 
#@url = https://spreadsheets.testingmachine.eu/sta-echarging/trigger
#@url = https://spreadsheets.opendatahub.com/sta-echarging/trigger


### Classification 
POST {{url}}
x-goog-changed: content
Accept: application/json
