@host = https://boxes.opendatahub.com
#@host = http://localhost:9002

POST {{host}}/json
Content-Type: application/json

[
	{
		"stationcode": "TEST-TEST-TEST",
		"mac": "abcdefgh"
	}
]

###
GET {{host}}/json?station-id=abc

###
GET {{host}}/trigger


https://mobility.share.opendatahub.com/json/syncStationStates/BluetoothStation
?prn=odh-mobility-dc-vehicletraffic-bluetooth
&prv=799912c053262d05ff81b9163ba7298907721c91
