@host = {{$dotenv A22_CONNECTOR_URL}}

### Authorize
# @name login
@token = {{login.response.body.SubscribeResult.sessionId}}
POST {{host}}/token
Content-Type: application/json
User-Agent: NOI/A22EventConnector
Accept: */*

{
	"request": {
		"username": "{{$dotenv A22_CONNECTOR_USR}}",
		"password": "{{$dotenv A22_CONNECTOR_PWD}}"
	}
}

### Get active events
POST {{host}}/eventi/lista/attivi
Content-Type: application/json
User-Agent: NOI/A22EventConnector
Accept: */*

{
	"request": {
		"sessionId": "{{token}}"
	}
}

### Get historical events
POST {{host}}/eventi/lista/storici
Content-Type: application/json
User-Agent: NOI/A22EventConnector
Accept: */*

{
	"request": {
		"sessionId": "{{token}}",
		"fromData": "/Date(1643414400000)/",
		"toData": "/Date(1643583600000)/"
	}
}

### Get brennerlec events
POST {{host}}/eventi/brennerlec/limititratte
Content-Type: application/json
User-Agent: NOI/A22EventConnector
Accept: */*

{
	"request": {
		"sessionId": "{{token}}",
		"fromData": "/Date(1643414400000)/",
		"toData": "/Date(1643583600000)/"
	}
}

