##### VSCODE / REST Client https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@endpoint = https://dati.retecivica.bz.it

# STATIONS
GET {{endpoint}}/services/meteo/v1/stations

# SENSORS
GET {{endpoint}}/services/meteo/v1/sensors

# TIME SERIES
GET {{endpoint}}/services/meteo/v1/timeseries
