# FROM maven:3-jdk-8
FROM maven:3-jdk-8-alpine

ARG JENKINS_GROUP_ID=1000
ARG JENKINS_USER_ID=1000

# RUN groupadd --gid $JENKINS_GROUP_ID jenkins && \
#    useradd --uid $JENKINS_USER_ID --gid $JENKINS_GROUP_ID --create-home jenkins

RUN addgroup -g $JENKINS_GROUP_ID jenkins && \
    adduser -D -u $JENKINS_USER_ID -G jenkins jenkins

RUN mkdir -p /var/log/opendatahub/data-collectors

COPY docker/entrypoint-java.sh /entrypoint-java.sh

ENTRYPOINT [ "/entrypoint-java.sh" ]
