##### VSCODE / REST Client https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# Create a .env file and set the corresponding variables
# See all $dotenv fields below

################################
### Schedule
################################

@auth_id = {{$dotenv AUTH_ID}}
@auth_password = {{$dotenv AUTH_PASSWORD}}

# other vars
@endpoint-schedule = https://api.aerocrs.com/v5/getSchedule

### Classification 
POST {{endpoint-schedule}}
Accept: application/json
auth_password: {{auth_password}}
auth_id: {{auth_id}}

{
  "aerocrs": {
    "parms": {
      "fltsFROMperiod": "2024/06/20",
      "fltsTOperiod": "2024/06/21",
      "codeformat": "IATA",
      "companycode": "BQ",
      "ssim": false,
      "soldonline": false
    }
  }
}

################################
### Fares
################################

# .env vars
@auth_id_fares = {{$dotenv AUTH_ID_FARES}}
@auth_password_fares = {{$dotenv AUTH_PASSWORD_FARES}}

# other vars
@endpoint-fares = https://api.aerocrs.com/v5/getFares
@start=2023/05/08
@end=2023/05/09
@from=BZO
@to=DUS

### Classification 
GET {{endpoint-fares}}
?start={{start}}
&end={{end}}
&from={{from}}
&to={{to}}
Accept: application/json
auth_password: {{auth_password_fares}}
auth_id: {{auth_id_fares}}

################################
### Realtime (API has IP filter, try with curl on docker hosts)
################################
GET https://dataprovider.ifly.aero:8443/fidsdataproviderproxy/dataProvider.ashx
Accept: application/json
Token: {{$dotenv AUTH_TOKEN_REAL_TIME}}
