##### VSCODE / REST Client https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# Create a .env file and set the corresponding variables
# See all $dotenv fields below


# Matomo Reporting API docs
# https://developer.matomo.org/api-reference/reporting-api

# .env vars
@token={{$dotenv MATOMO_API_TOKEN}}

# other vars
@endpoint=https://noi.matomo.cloud/


#########################
# Custom reports
#########################

GET {{endpoint}}
?module=API
&method=CustomReports.getCustomReport
&format=JSON
&idSite=1
&period=day
&date=yesterday
&idCustomReport=1
&flat=1
&token_auth={{token}}
Accept: application/json

#########################
# getPageUrl /de/transparente-verwaltung
#########################

GET {{endpoint}}
?module=API
&method=Actions.getPageUrl
&idSite=1
&period=day
&date=yesterday
&pageUrl=https://noi.bz.it/de/ueber-uns/transparente-verwaltung/allgemeine-bestimmungen
# &segment=pageUrl=@transparente-verwaltung
&format=JSON
&flat=1
&token_auth={{token}}
Accept: application/json

#########################
# getPageUrl /it/societa-trasparente
#########################

### 
GET {{endpoint}}
?module=API
&method=Actions.getPageUrl
&idSite=1
&period=day
&date=yesterday
&pageUrl=https://noi.bz.it/it/chi-siamo/societa-trasparente/disposizioni-generali
# &segment=pageUrl=@societa-trasparente,pageUrl=@amministrazione-trasparente
&format=JSON
&flat=1
&token_auth={{token}}
Accept: application/json