##### VSCODE / REST Client
# Create a .env file and set the corresponding variables
# See all $dotenv fields below



### Test push endpoint
POST https://parking.opendatahub.bz.it/dc-onstreet-parking-bz/json/pushRecords
Content-Type: application/json

{
	"devEUI": "001bc50670100544",
	"appEUI": "70b3d59b60000003",
	"fPort": 1,
	"gatewayCount": 1,
	"rssi": -115,
	"data": "gAAAAyoS9AABXlUj1AE6AAATiAAANQgANf4=",
	"parsedData": {
		"Magnitude": 5000,
		"Payload": "MEASURE",
		"Progtx": 13576,
		"Retries": 0,
		"Sensor-address": "sensor-1",
		"Status": "free",
		"Time": 1582638036,
		"Version": 58
	},
	"loRaSNR": -11,
	"frequency": 868300000,
	"dataRate": {
		"modulation": "LORA",
		"spreadFactor": 12,
		"bandwidth": 125
	},
	"devAddr": "e95ecbf3",
	"fCntUp": 4,
	"time": "2020-02-25T13:56:36.792579742Z",
	"encrypted": false,
	"format": "base64",
	"gateways": [
		{
			"mac": "00800000a0004693",
			"time": "0001-01-01T00:00:00Z",
			"timestamp": 1438540964,
			"frequency": 868300000,
			"channel": 1,
			"rfChain": 1,
			"crcStatus": 1,
			"codeRate": "4/5",
			"rssi": -115,
			"loRaSNR": -11,
			"size": 41,
			"dataRate": {
				"modulation": "LORA",
				"spreadFactor": 12,
				"bandwidth": 125
			}
		}
	]
}