### ALPERIA
# Not https (just port 80)
@hostalperia=http://api.alperia-emobility.eu

###
GET {{hostalperia}}/e-mobility/api/v3/chargingunits?includePartners=false
X-Caller-ID: NOI-Techpark
Accept: application/json


### NEVICAM
# unavailable at the moment, maybe deactivated completely?
@hostnevicam=https://mobility.nevicam.it

GET {{hostnevicam}}/apiv0/m2
X-Caller-ID: NOI-Techpark
Accept: application/json
apikey: {{$dotenv NEVICAM_API_KEY}}

### ROUTE220
#
@hostroute220=https://platform.evway.net

GET {{hostroute220}}/api/idm/getAllRoute220Stations
X-Caller-ID: NOI-Techpark
Accept: application/json
