##### VSCODE / REST Client
# Create a .env file and set the corresponding variables
# See all $dotenv fields below

@username={{$dotenv API_OAUTH_USERNAME}}
@password={{$dotenv API_OAUTH_PASSWORD}}
@secret={{$dotenv API_OAUTH_CLIENT_SECRET}}
@clientId={{$dotenv API_OAUTH_CLIENT_ID}}



### Get access token for the writer (LOCAL DEV)
# @name login
GET https://www.onecenter.info/oauth/token
?grant_type=password
&username={{username}}
&client_id={{clientId}}
&client_secret={{secret}}
&password={{password}}
Content-Type: application/x-www-form-urlencoded



### save token

@token = {{login.response.body.access_token}}

### GetFacilities
GET https://online.onecenter.info/api/Facility/GetFacilities
Authorization: Bearer {{token}}

### FacilityID
# 607440 Bressanone
# 608612 Brunico
GET https://online.onecenter.info/api/Facility/GetFreePlaces
?FacilityID=607440
Authorization: Bearer {{login.response.body.access_token}}
