# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

@host = {{$dotenv DZT_BASE_URL}}
@apikey = {{$dotenv DZT_API_KEY}}

###
# Get a list of available EChargingStations, paging is available. Max page size is 15
POST {{host}}/api/ts/v2/kg/things?filterDsList=https%3A%2F%2Fsemantify.it%2Fds%2FE85TgOxMg
page: 0
page-size: 5
Content-Type: application/ld+json
x-api-key: {{apikey}}

{
    "@context": {
    "ometa": "http://onlim.com/meta/",
    "sq": "http://www.onlim.com/shapequery/",
    "@vocab": "http://www.onlim.com/shapequery/"
  },
    "sq:query":[
        {
          "ometa:dateModified":{
            "sq:value":"2023-02-23T19:00:00",
            "sq:op":">",
            "sq:datatype":"dateTime"
          }
        }
    ]    
}

###
# get details of single Station with ID 100001001
GET {{host}}/api/ts/v1/kg/things/100001001
?ns=http%3A%2F%2Fonlim.com%2Fentity%2FLadestationen-Api-Bund%2FECarChargingStation%2F
Content-Type: application/json
x-api-key: {{apikey}}